version: "3.7"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
       - ./:/postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - "9000:9000"