server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
    context-path: '/'

spring:
  resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?currentSchema=sgpd
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Postgres2022!}
    initialization-mode: always
    connectionTestQuery: 'SELECT 1'
  flyway:
    baselineOnMigrate: true

  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: update
    generate-ddl: true

management:
  endpoint:
    health:
      show-details: always